export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST';
export const CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS';
export const CHARACTERS_FAILURE = 'CHARACTERS_FAILURE';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_PAGE_COUNT = 'CHANGE_PAGE_COUNT';

export const CHARACTER_REQUEST = 'CHARACTER_REQUEST';
export const CHARACTER_SUCCESS = 'CHARACTER_SUCCESS';
export const CHARACTER_FAILURE = 'CHARACTER_FAILURE';